#!/bin/bash

# adjust the variables section below
#
# then: place this in /etc/init.d
# then: chmod +x /etc/init.d/sonos-denon-monitor
# then: update-rc.d sonos-denon-monitor defaults
#
# start daemon with /etc/init.d/sonos-denon-monitor start
# stop it with /etc/init.d/sonos-denon-monitor stop

DAEMON=/volume1/ROSS-STORAGE/sonos-denon-monitor/sonos-denon-monitor.sh
#ARGS=/volume1/ROSS-STORAGE/sonos-denon-monitor/sonos-denon-monitor.py
ARGS=
LOG=/volume1/ROSS-STORAGE/sonos-denon-monitor/sonos-denon-monitor.log
PIDFILE=/var/run/sonos-denon-monitor.pid
USER=phunkyfish
GROUP=users

case "$1" in
  start)
    echo "Starting server"
    /sbin/start-stop-daemon --start --pidfile $PIDFILE \
        --user $USER --group $GROUP \
        -b --make-pidfile \
        --chuid $USER \
        --startas /bin/bash -- -c "exec $DAEMON $ARGS >>$LOG 2>&1"
    ;;
  stop)
    echo "Stopping server"
    parentPid=$(<"$PIDFILE")
    for i in `ps -ef| awk '$3 == '${parentPid}' { print $2 }'`
    do
        echo killing $i
        kill -9 $i
    done
    /sbin/start-stop-daemon --stop --pidfile $PIDFILE --verbose
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac

exit 0
